version: '3.4'

services:
  webserver:
    container_name: webserver
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: WEBServer/Dockerfile
    environment:
      DBConnection: Host=webdb-master;Username=postgres;Password=root;Database=webdb
    ports:
      - 5000:80

  webserver-1:
    container_name: webserver-1
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: WEBServer/Dockerfile
    environment:
      DBConnection: Host=webdb-master;Username=postgres;Password=root;Database=webdb
    ports:
      - 5001:80

  webserver-2:
    container_name: webserver-2
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: WEBServer/Dockerfile
    environment:
      DBConnection: Host=webdb-master;Username=postgres;Password=root;Database=webdb
    ports:
      - 5002:80
  
  webserver-mirror:
    container_name: webserver-mirror
    image: ${DOCKER_REGISTRY-}webserver
    build:
      context: .
      dockerfile: WEBServer/Dockerfile
    environment:
      DBConnection: Host=webdb-slave;Username=readonlyuser;Password=readonlypassword;Database=webdb
    ports:
      - 5003:80

  webdb-master:
    container_name: webdb-master
    image: 'bitnami/postgresql:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      # - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_DATABASE=webdb
    volumes:
      - ./pg_data_master:/bitnami/postgresql

  webdb-slave:
    container_name: webdb-slave
    image: 'bitnami/postgresql:latest'
    ports:
      - 5433:5432
    depends_on:
      - webdb-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=webdb-master
      - POSTGRESQL_PASSWORD=root
      - POSTGRESQL_MASTER_PORT_NUMBER=5432

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      # - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/:/etc/nginx/"
    ports:
      - 80:80
      - 433:433

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@example.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    ports:
      - 8000:80
